# Generated by Django 5.1.6 on 2025-03-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0009_rename_file_certificate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='postal_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
