# Generated by Django 5.1.6 on 2025-03-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0010_staffdetails_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='postal_code',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
